Update catch.hpp to Version 2.13.10
Required to fix build issue when profiling:
error: unrecognized instruction mnemonic, did you mean: bit, cnt, hint, ins, not?
CATCH_BREAK_INTO_DEBUGGER();

Fix:
https://github.com/catchorg/Catch2/commit/a25c1a24af8bffd35727a888a307ff0280cf9387

Source:
https://github.com/catchorg/Catch2/releases/download/v2.13.10/catch.hpp